language: java
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
jdk:
  - oraclejdk8
  - openjdk8
env:
  global:
    - secure: "OyIH258fM4abA0W34Lsl2Ucd+393pGO0TS2+d7YZ82w5+iJMDJQemdukrnJ49Ru7yejYNfEKohfGBPEu9LrMJ0YhgiQoYvYw1J0Fyj2WyPfW4uppdOupWAABhZ608grhiekqY6bWaYJTtWV9JBtieKIhNKrU3pPr7PYHo87DA1BMhaOnHVTYz+nXOMWcSZnBEVhhyiQ7pwtM86Qj5kqF+fXg47eI50np8rVAqZmGv6dypXmnJIZsE2RiMFO9dF7gXdOtd0MDhoZLin8CPMpo7VTn/bk+En7EXAsn7Y1d6tf8/aHGpPwU3EQ22Vp0Ady3pYNw8ByS6T38hzvDisK2dIW63D26hHaB20bn5TOlqAKO+M30NPgImiYtyE2WN9QgZc5NoJ1CvNK6DIqwp4ymotFaPDifETC5U8VrNecnv4bm+lBNCZvlB8yP8PziAGV+V30t9waMdI9KOV+yBGIWug7GM/MhWdo4Ew/rf3h7WAGy4WF1QVvHYXhdWfH5SxXmCyR24S3/r9mecktecDXabUZKY647Qqg5jQPKgy3X/oK7Y4mXfqAtzaY7HRY5nn7LxE3szT5n82ulIxDj7HOIRmbo66v7zrrL0XMgZqmVEp/wJGIT4QOziMZCYIgUnWe+gonLqCNjJaKiwJgKpI03thHBgSV9lDJXUT96emqTD5o="
    - secure: "xBYC+nh2x5f0vbHlDpbcBTS/WN6cO56FazDj1rwfhDQZsRTzcm5IqpbACvod/zCtCRbmAwDk2cD1Fo/gEyOiI91WPluEFZUU/rgWFU+hUobfKHXXs4Q4jsTMj+nuMtrxybTw4rVbaknvSSYRGHTU2VttRbnV6jnE3zRGKIjfT7aSClkEE7AcaRowdPnavGphT5JAYII+DhTQuBiT94GPa0a59Cd41Q6OCi10Um1PwxSl7bB38fzLjv81wjDmizsB2Tzn2oV7kM8hsLNBHVEgmORWcL/eA4pD6PkMosm4F78EmeFX/2w1Z190DrSfvxJlXmEsxf2IZ56EMR8YnGLIdbtL/Fpmu7bxoyzpkzg2TOVkGSGK7ri+zbF5J77BGSSMOymMYb3wev88j19nVEOtw7qXeb9ku4nZjtLQie82nroaJcqw84j6tEn9BAp+uqke7Bs+h1uwH4J4kahRPYf3Sm0L9aGf7Y0Afp9rroeZWtKLCdH74lSCZcLd082lBYueh3g5fHxJEnPqQ2xfO1EqAcykm/vHnMKubR75ECgU2aS/gCW5tqJlSf4RHEiXHa5Bl6fF0K9oYeNCmrh9siyZzGjK3BZKVp8F75wTiG5oLAF3CpYDuygGxRKEJEFYBgQohCv/wIOLyjGhx59tLbJB3e+/mWuhOcFQy3POaJq/Scg="

after_success:
  - .buildscript/deploy_snapshot.sh
